### PR TITLE
Update release

### PR DESCRIPTION
**Pull request by xtreme-jason-smith**
This fixes some script issues and adds support to install Strawberry Perl 64bit

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
@xtreme-jason-smith thanks for the PR!

Only question we have is if you could add a bosh property on the `mingw32` and `mingw64` jobs that lets you choose whether you want them on the path.

The change in this PR adds `mingw32` binaries to the path but that will conflict with `mingw64` binaries if both are deployed on the same VM (which is what we do in our concourse workers). If you add the property that lets you choose (and default the `mingw64` property to `true` and the `mingw32` property to `false`) then these jobs can coexist.

**Comment by xtreme-jason-smith** [comment]
@sunjayBhatia That's a good idea. I will update the code appropriately when I have some time, and update the PR.

**Comment by sunjayBhatia** [comment]
@xtreme-jason-smith sweet, thanks!

**Comment by zmackie** [comment]
Closing in favor of https://github.com/cloudfoundry/windows-tools-release/pull/5

**Pull request closed without merging**
